import time

from fastapi import APIRouter, HTTPException, status

from backend.Util.constants import file_cache
from backend.Util.enums import Tags

router = APIRouter(prefix="/debug")

def verify_parsed_data(file_id: str):
    parsed_data = file_cache.get(file_id)
    if not parsed_data:
        print(file_cache)
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="File expired or not found"
        )
    return parsed_data

@router.get("/user-messages", tags=[Tags.Debug], description="Displays the latest 1000 messages.")
def user_messages(file_id: str):
    parsed_data = verify_parsed_data(file_id)
    return {"parsed_data": parsed_data.user_messages[-1000:]}

@router.get("/system-messages", tags=[Tags.Debug], description="Displays all the messages generated by system.")
def system_messages(file_id: str):
    parsed_data = verify_parsed_data(file_id)
    return {"system_messages": parsed_data.system_messages}