from enum import Enum

# Tags for different routes and paths
class Tags(Enum):
    Status = "Status"
    Upload = "Upload"
    Analyse_Users = "Analyse Users"
    Analyse_Messages = "Analyse Messages"
    Analyse_Time = "Analyse Time"
    Analyse_Events = "Analyse Events"

# Different types of messages generated by whatsapp
class SysMsgActions(str, Enum):
    CreateGroup = "created group"
    AddUser = "added"
    ChangeGrpDesc = "changed the group description"
    ChangeGrpIcon = "changed this group's icon"
    RemoveGrpIcon = "deleted this group's icon"
    ChangeGrpName = "changed the group name from"
    PinMsg = "pinned a message"
    AddAdmin = "now an admin"
    RemoveAdmin = "no longer an admin"
